[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[mouse]

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[colors.bright]
black = "0x545454"
blue = "0x5454ff"
cyan = "0x54ffff"
green = "0x54ff54"
magenta = "0xff54ff"
red = "0xff5454"
white = "0xf3f3f3"
yellow = "0xedd400"

[colors.cursor]
cursor = "0x000000"
text = "0xffffff"

[colors.normal]
black = "0x000000"
blue = "0x0000aa"
cyan = "0x00aaaa"
green = "0x00aa00"
magenta = "0xad7fa8"
red = "0xcc0000"
white = "0xeeeeec"
yellow = "0xc4a000"

[colors.primary]
background = "0xddf4d4"
foreground = "0x1e1e1e"

[debug]
log_level = "OFF"
print_events = false

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "Roboto Mono"
style = "Bold"

[font.bold_italic]
family = "Roboto Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Roboto Mono"
style = "Italic"

[font.normal]
family = "Roboto Mono"
style = "Medium"

[font.offset]
x = 0
y = 0

[scrolling]
history = 5000
multiplier = 3

[window]
decorations = "full"
startup_mode = "Windowed"
title = "Alacritty"

[window.padding]
x = 0
y = 0

[keyboard]
